server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/login_sample
    driver-class-name: org.mariadb.jdbc.Driver
    username: login_sample
    password: login_sample
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
